<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
 $form = $this->form;
 $messages = $this->messages;
 $data = $this->data;
 $edit_flag = $this->edit_flag;
 $loginuserGroup = $this->loginuserGroup;
 sapp_Global::generateClientValidations($this->form);
// $requisition_view_helper = $this->Requisition();

if($this->nodata == 'nodata') {
    ?>
    <div class="ml-alert-1-info">
        <div class="style-1-icon info"></div>No data found.
    </div>
 <?php } else { ?>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
<div class="total-form-controller">
    <?php echo $form->id;
    echo $this->form->email_cnt;
         if(isset($messages['email_cnt']))
         {
?> <div class="ml-alert-1-info">
		<div class="style-1-icon info"></div>
		<?php echo $messages['email_cnt'] ;?>	
	</div>
<?php 
         }
        ?>

    <input type="hidden" name="edit_flag" value="<?php echo $edit_flag;?>" />
    <input type="hidden" name="shiftpayroll" id="shiftpayroll" value="<?php echo $data['shiftpayroll'];?>" />
    <div class="new-form-ui">
        <label>Employee ID</label>
        <div class="division"><?php echo $form->employee_id;?> </div>
    </div>

    <div class="new-form-ui">
        <label class="required">Starting Date</label>
        <div class="division"><?php echo $form->starting_date;?></div>
    </div>

    <div class="new-form-ui">
        <label class="required">Employee Name</label>
        <div class="division"><?php echo $form->employee_name;?></div>
    </div>

    <div class="new-form-ui">
        <label class="required">Department</label>
        <div class="division"><?php echo $form->department;?></div>
    </div>

    <div class="new-form-ui textareaheight">
        <label>Comments</label>
        <div class="division"><?php echo $form->comments;?>
            <span id="errors-comments" class="errors"><?php echo (isset($messages['comments'])?$messages['comments']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label class="required">Gross Base Salary</label>
        <div class="division"><?php echo $form->grossbase_salary;?></div>
    </div>

    <div class="new-form-ui">
        <label>Sick leave in Days</label>
        <div class="division"><?php echo $form->sick_leavedays;?>
            <span id="errors-sick_leavedays" class="errors"><?php echo (isset($messages['sick_leavedays'])?$messages['sick_leavedays']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Standby in Hours</label>
        <div class="division"><?php echo $form->standby_hours;?>
            <span id="errors-standby_hours" class="errors"><?php echo (isset($messages['standby_hours'])?$messages['standby_hours']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Overtime in Hours</label>
        <div class="division"><?php echo $form->overtime_hours;?>
            <span id="errors-overtime_hours" class="errors"><?php echo (isset($messages['overtime_hours'])?$messages['overtime_hours']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Addition Role/Position</label>
        <div class="division"><?php echo $form->addition_rollposition;?>
            <span id="errors-addition_rollposition" class="errors"><?php echo (isset($messages['addition_rollposition'])?$messages['addition_rollposition']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Weekend/National Holidays</label>
        <div class="division"><?php echo $form->weekend_nationaldays;?>
            <span id="errors-weekend_nationaldays" class="errors"><?php echo (isset($messages['weekend_nationaldays'])?$messages['weekend_nationaldays']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Annual leave Days</label>
        <div class="division"><?php echo $form->annual_leavedays;?>
            <span id="errors-annual_leavedays" class="errors"><?php echo (isset($messages['annual_leavedays'])?$messages['annual_leavedays']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Daily allowance</label>
        <div class="division"><?php echo $form->daily_allowance;?>
            <span id="errors-daily_allowance" class="errors"><?php echo (isset($messages['daily_allowance'])?$messages['daily_allowance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Deduct/Add from Gross Salary</label>
        <div class="division"><?php echo $form->deductadd_salary;?>
            <span id="errors-deductadd_salary" class="errors"><?php echo (isset($messages['deductadd_salary'])?$messages['deductadd_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Gross Salary</label>
        <div class="division"><?php echo $form->gross_salary;?>
            <span id="errors-gross_salary" class="errors"><?php echo (isset($messages['gross_salary'])?$messages['gross_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label class="required">Contract Date <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo MEDIA_PATH;?>images/help.png" /></label>
        <div class="division"><?php echo $form->contract_date;?></div>
    </div>

    <div class="new-form-ui">
        <label>Work Days</label>
        <div class="division"><?php echo $form->work_days;?>
            <span id="errors-work_days" class="errors"><?php echo (isset($messages['work_days'])?$messages['work_days']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Monthly Gross Salary</label>
        <div class="division"><?php echo $form->monthlygross_salary;?>
            <span id="errors-monthlygross_salary" class="errors"><?php echo (isset($messages['monthlygross_salary'])?$messages['monthlygross_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Contribution Calculated Salary</label>
        <div class="division"><?php echo $form->contribution_salary;?>
            <span id="errors-contribution_salary" class="errors"><?php echo (isset($messages['contribution_salary'])?$messages['contribution_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Employee Social Insurance</label>
        <div class="division"><?php echo $form->employeesocial_insurance;?>
            <span id="errors-employeesocial_insurance" class="errors"><?php echo (isset($messages['employeesocial_insurance'])?$messages['employeesocial_insurance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Employee Health Insurance</label>
        <div class="division"><?php echo $form->employeehealth_insurance;?>
            <span id="errors-employeehealth_insurance" class="errors"><?php echo (isset($messages['employeehealth_insurance'])?$messages['employeehealth_insurance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Total of Employee Insurance</label>
        <div class="division"><?php echo $form->employeetotal_insurance;?>
            <span id="errors-employeetotal_insurance" class="errors"><?php echo (isset($messages['employeetotal_insurance'])?$messages['employeetotal_insurance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Employer Social Insurance</label>
        <div class="division"><?php echo $form->employersocial_insurance;?>
            <span id="errors-employersocial_insurance" class="errors"><?php echo (isset($messages['employersocial_insurance'])?$messages['employersocial_insurance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Employer Health Insurance</label>
        <div class="division"><?php echo $form->employerhealth_insurance;?>
            <span id="errors-employerhealth_insurance" class="errors"><?php echo (isset($messages['employerhealth_insurance'])?$messages['employerhealth_insurance']:"");?></span>
        </div>
    </div>


    <div class="new-form-ui">
        <label>Total of Employer Insurance</label>
        <div class="division"><?php echo $form->employertotal_insurance;?>
            <span id="errors-employertotal_insurance" class="errors"><?php echo (isset($messages['employertotal_insurance'])?$messages['employertotal_insurance']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Salary withholding taxs are calculated</label>
        <div class="division"><?php echo $form->whtaxpaided_salary;?>
            <span id="errors-whtaxpaided_salary" class="errors"><?php echo (isset($messages['whtaxpaided_salary'])?$messages['whtaxpaided_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Progresive withholding Tax</label>
        <div class="division"><?php echo $form->progresive_whtax;?>
            <span id="errors-progresive_whtax" class="errors"><?php echo (isset($messages['progresive_whtax'])?$messages['progresive_whtax']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Net Salary paid through Bank</label>
        <div class="division"><?php echo $form->bankpaid_salary;?>
            <span id="errors-bankpaid_salary" class="errors"><?php echo (isset($messages['bankpaid_salary'])?$messages['bankpaid_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Adds to Net Salary</label>
        <div class="division"><?php echo $form->addtax_salary;?>
            <span id="errors-addtax_salary" class="errors"><?php echo (isset($messages['addtax_salary'])?$messages['addtax_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Withhold from Net Salary</label>
        <div class="division"><?php echo $form->whtax_salary;?>
            <span id="errors-whtax_salary" class="errors"><?php echo (isset($messages['whtax_salary'])?$messages['whtax_salary']:"");?></span>
        </div>
    </div>

    <div class="new-form-ui">
        <label>Total Net Salary</label>
        <div class="division"><?php echo $form->total_bankpaid_salary;?>
            <span id="errors-total_bankpaid_salary" class="errors"><?php echo (isset($messages['total_bankpaid_salary'])?$messages['total_bankpaid_salary']:"");?></span>
        </div>
    </div>

    <div class="claerall fullwidth fltleft"></div>

    <div class="new-form-ui-submit">
        <?php echo $form->submit;?>
        <button type="button" id="Cancel" name="Cancel" onclick="window.location.href='<?php echo BASE_URL; ?>shiftpayroll';">Cancel</button>
    </div>



</div>
</form>
<?php }?>

<script type="text/javascript" src="<?php echo MEDIA_PATH;?>js/jquery-te.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/jquery-te.css" />
<script type="text/javascript" language="javascript">
    var yearrange = <?php echo "'".YEAR.':'.(date('Y')+20)."'"; ?>;
    $(document).ready(function() {

        $("#contract_date").datepicker({
            showOn: "both",
            buttonImage: "<?php echo MEDIA_PATH;?>images/cal.png",
            buttonImageOnly: true,
            yearRange: yearrange,

            buttonText: "",
            changeMonth: true,
            changeYear: true,
            dateFormat: "<?php echo DATEFORMAT_JS;?>",
            // minDate: '+1d',
            showButtonPanel: true,
            onClose: function () {
                $('#onboard_date').trigger('blur');
            }
        });

        $("#starting_date").datepicker({
            showOn: "both",
            buttonImage: "<?php echo MEDIA_PATH;?>images/cal.png",
            buttonImageOnly: true,
            yearRange: yearrange,

            buttonText: "",
            changeMonth: true,
            changeYear: true,
            dateFormat: "<?php echo DATEFORMAT_JS;?>",
            // minDate: '+1d',
            showButtonPanel: true,
            onClose: function () {
                $('#onboard_date').trigger('blur');
            }
        });

        $('#req_no_positions').change(function () {
            check_zerovalue(this);
        });


        var change_values = function(){

            var $grossbase_salary = Number($('#grossbase_salary').val())?Number($('#grossbase_salary').val()):0;
            var $gross_salary = Number($('#gross_salary').val())?Number($('#gross_salary').val()):0;
            var $sick_leavedays = Number($('#sick_leavedays').val())?Number($('#sick_leavedays').val()):0;
            var $standby_hours = Number($('#standby_hours').val())?Number($('#standby_hours').val()):0;
            var $overtime_hours = Number($('#overtime_hours').val())?Number($('#overtime_hours').val()):0;
            var $addition_rollposition = Number($('#addition_rollposition').val())?Number($('#addition_rollposition').val()):0;
            var $weekend_nationaldays = Number($('#weekend_nationaldays').val())?Number($('#weekend_nationaldays').val()):0;
            var $annual_leavedays = Number($('#annual_leavedays').val())?Number($('#annual_leavedays').val()):0;
            var $daily_allowance = Number($('#daily_allowance').val())?Number($('#daily_allowance').val()):0;
            var $deductadd_salary = Number($('#deductadd_salary').val())?Number($('#deductadd_salary').val()):0;
            var $work_days = Number($('#work_days').val())?Number($('#work_days').val()):0;
            var $whtax_salary = Number($('#whtax_salary').val())?Number($('#whtax_salary').val()):0;
            var $addtax_salary = Number($('#addtax_salary').val())?Number($('#addtax_salary').val()):0;
            var $shiftpayroll = Number($('#shiftpayroll').val());


            // Variables initialize

            var $monthlygross_salary = 0;
            var $contribution_salary = 0;
            var $employeesocial_insurance = 0;
            var $employeehealth_insurance = 0;
            var $employeetotal_insurance = 0;
            var $employersocial_insurance = 0;
            var $employerhealth_insurance = 0;
            var $employertotal_insurance = 0;
            var $whtaxpaided_salary = 0;
            var $progresive_whtax = 0;
            var $bankpaid_salary = 0;
            var $total_bankpaid_salary = 0;
            // var $gross_salary = 0;


            if($shiftpayroll){
                $monthlygross_salary = $gross_salary;
            } else {
                $gross_salary = $grossbase_salary + $deductadd_salary;

                if($sick_leavedays){
                    // $work_days = $work_days - $sick_leavedays;
                    $gross_salary = $gross_salary - ($grossbase_salary/21)*$sick_leavedays*0.2;
                }
                if($standby_hours){
                    $gross_salary = $gross_salary - $standby_hours*120;
                }
                if($overtime_hours){
                    $gross_salary = $gross_salary + $overtime_hours*($grossbase_salary/21/8)*0.25;
                }
                if($addition_rollposition){
                    $gross_salary = $gross_salary + $addition_rollposition;
                }
                if($weekend_nationaldays){
                    $gross_salary = $gross_salary + $weekend_nationaldays*4500;
                }
                if($daily_allowance){
                    $gross_salary = $gross_salary + $daily_allowance*400;
                }

                $monthlygross_salary = $gross_salary * $work_days/21;
            }


            $contribution_salary = $monthlygross_salary>=105850?105850:($monthlygross_salary<=24000?24000:$monthlygross_salary);
            $employeesocial_insurance = $contribution_salary * 0.095;
            $employeehealth_insurance = $monthlygross_salary * 0.017;
            $employeetotal_insurance = $employeesocial_insurance + $employeehealth_insurance;
            $employersocial_insurance = $contribution_salary * 0.15;
            $employerhealth_insurance = $monthlygross_salary * 0.017;
            $employertotal_insurance = $employersocial_insurance + $employerhealth_insurance;
            $whtaxpaided_salary = $monthlygross_salary;

            if($whtaxpaided_salary <= 30000){
                $progresive_whtax = 0;
            }else if($whtaxpaided_salary > 130000){
                $progresive_whtax = ($whtaxpaided_salary - 130000)*0.23 +13000;
            }else{
                $progresive_whtax = ($whtaxpaided_salary - 30000)*0.13;
            }

            $bankpaid_salary = $whtaxpaided_salary - $employeetotal_insurance - $progresive_whtax;

            $total_bankpaid_salary = $bankpaid_salary - $whtax_salary + $addtax_salary;



            // Setting Values of each elements

            $('#gross_salary').val(Math.round($gross_salary));
            $('#monthlygross_salary').val(Math.round($monthlygross_salary));
            $('#contribution_salary').val(Math.round($contribution_salary));
            $('#employeesocial_insurance').val(Math.round($employeesocial_insurance));
            $('#employeehealth_insurance').val(Math.round($employeehealth_insurance))
            $('#employeetotal_insurance').val(Math.round($employeetotal_insurance));
            $('#employersocial_insurance').val(Math.round($employersocial_insurance));
            $('#employerhealth_insurance').val(Math.round($employerhealth_insurance));
            $('#employertotal_insurance').val(Math.round($employertotal_insurance));
            $('#whtaxpaided_salary').val(Math.round($whtaxpaided_salary));
            $('#progresive_whtax').val(Math.round($progresive_whtax));
            $('#bankpaid_salary').val(Math.round($bankpaid_salary));
            $('#total_bankpaid_salary').val(Math.round($total_bankpaid_salary));

        }

        $('#comment').change(function(){
            change_values();
        });

        $('#sick_leavedays').change(function(){
            change_values();
        });

        $('#standby_hours').change(function(){
            change_values();
        });

        $('#overtime_hours').change(function(){
            change_values();
        });

        $('#annual_leavedays').change(function(){
            change_values();
        });

        $('#weekend_nationaldays').change(function(){
            change_values();
        });

        $('#daily_allowance').change(function(){
            change_values();
        });

        $('#deductadd_salary').change(function(){
            change_values();
        });

        $('#work_days').change(function(){
            change_values();
        });

        $('#whtax_salary').change(function(){
            change_values();
        });
        $('#addtax_salary').change(function(){
            change_values();
        });



    });
</script>